In [7]:
import numpy as np

In [9]:
a = np.arange(6)
type(a)

numpy.ndarray

In [10]:
a

array([0, 1, 2, 3, 4, 5])

In [13]:
a[:]

array([0, 1, 2, 3, 4, 5])

In [17]:
a2 = a[np.newaxis, :]

In [18]:
a2.shape

(1, 6)

In [19]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [20]:
print(a[0])

[1 2 3 4]


In [23]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
a[1]

array([5, 6, 7, 8])

In [28]:
a = np.array([1, 2, 3])

In [30]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.empty(2)

array([0., 0.])

In [32]:
np.arange(4)

array([0, 1, 2, 3])

In [33]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [35]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8]) 

In [36]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [38]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [40]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [42]:
array_example.ndim

3

In [43]:
array_example.size

24

In [44]:
array_example.shape

(3, 2, 4)

In [45]:
a = np.arange(6)

In [46]:
print(a)

[0 1 2 3 4 5]


In [47]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [48]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [49]:
a = np.array([1, 2, 3, 4, 5, 6])

In [50]:
a.shape

(6,)

In [51]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [52]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [53]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [54]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [55]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [56]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [57]:
data = np.array([1, 2, 3])

In [58]:
data[1]

2

In [59]:
data[0:2]

array([1, 2])

In [60]:
data[1:]

array([2, 3])

In [61]:
data[-2:]

array([2, 3])

In [62]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [63]:
print(a[a < 5])

[1 2 3 4]


In [64]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [65]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [66]:
c = a[(a > 2) & (a < 11)]
print(c)


[ 3  4  5  6  7  8  9 10]


In [67]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [68]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [69]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [70]:
list_of_coordinates= list(zip(b[0], b[1]))

In [71]:
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [72]:
print(a[b])

[1 2 3 4]


In [73]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [74]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [78]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [79]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [80]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [81]:
x = np.arange(1, 25).reshape(2, 12)

In [82]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [83]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [84]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [85]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [86]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [87]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [88]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [92]:
data - ones

array([0, 1])

In [93]:
data * data

array([1, 4])

In [94]:
data / data

array([1., 1.])

In [95]:
a = np.array([1, 2, 3, 4])

In [96]:
a.sum()

10

In [97]:
b = np.array([[1, 1], [2, 2]])

In [98]:
b.sum(axis=0)

array([3, 3])

In [99]:
b.sum(axis=1)

array([2, 4])

In [100]:
data = np.array([1.0, 2.0])

In [101]:
data * 1.6

array([1.6, 3.2])

In [102]:
data.max()

2.0

In [103]:
data.min()

1.0

In [104]:
data.sum()

3.0

In [105]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [106]:
a.sum()

4.8595784

In [107]:
a.min()

0.05093587

In [108]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [109]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [110]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [111]:
data[0, 1]

2

In [112]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [113]:
data[0:2, 0]

array([1, 3])

In [114]:
data.max()

6

In [115]:
data.min()

1

In [116]:
data.sum()

21

In [117]:
data = np.array([[1, 2], [5, 3], [4, 6]])

In [118]:
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [120]:
data.max(axis=0)

array([5, 6])

In [121]:
data.max(axis=1)

array([2, 5, 6])

In [122]:
data = np.array([[1, 2], [3, 4]])

In [123]:
ones = np.array([[1, 1], [1, 1]])

In [124]:
data + ones

array([[2, 3],
       [4, 5]])

In [125]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [126]:
ones_row = np.array([[1, 1]])

In [127]:
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [128]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [129]:
np.ones(3)

array([1., 1., 1.])

In [130]:
np.zeros(3)

array([0., 0., 0.])

In [131]:
rng = np.random.default_rng()

In [132]:
rng.random(3)

array([0.07003858, 0.67263573, 0.4735939 ])

In [134]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [135]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [136]:
rng.random((3,2))

array([[0.98489509, 0.91491166],
       [0.04663452, 0.21263067],
       [0.31116516, 0.29932476]])

In [137]:
rng.integers(5, size=(2, 4))

array([[2, 1, 4, 1],
       [3, 0, 4, 3]])

In [138]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [139]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [140]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [141]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)


[3 2 2 2 1 1 1 1 1 1]


In [142]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [143]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [144]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [145]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [146]:
print(indices)

[0 1 2]


In [147]:
print(occurrence_count)

[2 1 1]


In [148]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [149]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [150]:
arr = np.arange(6).reshape((2, 3))

In [151]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [152]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [153]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [154]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [155]:
reversed_arr = np.flip(arr)

In [156]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [157]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [158]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [159]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [160]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [161]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [162]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [163]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [164]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [165]:
a1 = x.flatten()

In [166]:
a1[0] = 99

In [167]:
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [168]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [169]:
a2 = x.ravel()

In [170]:
a2[0] = 98

In [171]:
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [172]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
